export const DIRT_TYPES = {
  dust: {
    id: "dust",
    interactionType: "tap",
    toolId: "squeegee",
    hitsToClean: 2,
    color: 0xd8d8c0,
  },
  "bird-poop": {
    id: "bird-poop",
    interactionType: "hold",
    toolIds: ["sponge"],
    requiredSprayStage: 8,
    holdDurationRange: [2000, 3000],
    color: 0xf5f5f5,
    textureKey: "dirt-bird-poop",
    file: "bird_poop.svg",
  },
  "hand-prints": {
    id: "hand-prints",
    interactionType: "wipe",
    toolIds: ["squeegee", "sponge"],
    requiredSprayStage: 1,
    hitsToClean: 6,
    color: 0xc9b8a8,
    textureKey: "dirt-hand-prints",
    file: "hand_prints.svg",
  },
  sticker: {
    id: "sticker",
    interactionType: "wipe",
    toolIds: ["squeegee"],
    requiredSprayStage: 0,
    hitsToClean: 144,
    color: 0xdba844,
    stages: [
      { textureKey: "sticker-stage-1", file: "stickers/sticker_peel_stage_1.svg" },
      { textureKey: "sticker-stage-2", file: "stickers/sticker_peel_stage_2.svg" },
      { textureKey: "sticker-stage-3", file: "stickers/sticker_peel_stage_3.svg" },
      { textureKey: "sticker-stage-4", file: "stickers/sticker_peel_stage_4.svg" },
    ],
  },
};
